### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by kobe-koto** [IcyBlue17/Class-namer#1]
這個項目實沒有最低學號，沒有GUI。
我想老師可能不會用吧（）

順帶提一句，我是你同校的學生哦

**Comment by IcyBlue17** [comment]
gui版本在教师电脑上被老师删了，因为有人玩游戏招来老师清理D盘
甚至个人认为gui版本难度低于这个版本，因为GUI版本本质上就是 _tk库当Button被点击出发一个事件CH，然后Label打印出random库提供的随机数_，没有像这个版本这么多**杂七杂八**的东西，写起来挺简单的
关于最低学号的话，个人认为用到这玩意的机会比较少，可以不加，可以考虑加个设置菜单额外设置一下最低

**Comment by kobe-koto** [comment]
最低學號多加個input啊（）

順便吐槽一句，JavaScript的random像屎似的

**Comment by IcyBlue17** [comment]
对的

**Comment by IcyBlue17** [comment]
现在发0.3 xd
